//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildCrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PermissionsToStaff
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string MemberPermission { get; set; }
        public string MembershipPlanPermission { get; set; }
        public string EventsPermission { get; set; }
        public string VendorsPermission { get; set; }
        public string MenuItemsPermission { get; set; }
        public string FoodBillingEditPermission { get; set; }
    
        public virtual tbl_Profile tbl_Profile { get; set; }
    }
}
