//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildCrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Vendors
    {
        public tbl_Vendors()
        {
            this.tbl_Inventory = new HashSet<tbl_Inventory>();
            this.tbl_BarInventory = new HashSet<tbl_BarInventory>();
        }
    
        public int ID { get; set; }
        public string Vendor_First_Name { get; set; }
        public string Vendor_Last_Name { get; set; }
        public string Contact_No { get; set; }
        public string EmailID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<bool> IsNewApproved { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string AddedBy { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual ICollection<tbl_Inventory> tbl_Inventory { get; set; }
        public virtual ICollection<tbl_BarInventory> tbl_BarInventory { get; set; }
    }
}
