//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildCrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MembersBillingDetails
    {
        public int ID { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string Mode_Of_Payment { get; set; }
        public string Cheque_No { get; set; }
        public string BankName { get; set; }
        public string Payment_Date { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
