//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildCrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Profile
    {
        public tbl_Profile()
        {
            this.tbl_PermissionsToStaff = new HashSet<tbl_PermissionsToStaff>();
            this.tbl_UserGroup = new HashSet<tbl_UserGroup>();
            this.tbl_UserMembership = new HashSet<tbl_UserMembership>();
            this.tbl_UsersStay = new HashSet<tbl_UsersStay>();
            this.tbl_VoucherUsedByUser = new HashSet<tbl_VoucherUsedByUser>();
        }
    
        public int ID { get; set; }
        public string F_Name { get; set; }
        public string L_Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public string DOB { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> EmailNotifications { get; set; }
        public Nullable<int> UserType { get; set; }
        public string Password { get; set; }
        public string AddedBy { get; set; }
        public Nullable<bool> NewUsrBySuperApprv { get; set; }
        public Nullable<bool> DelUsrBySuperApprv { get; set; }
        public Nullable<bool> Walk_In_Member { get; set; }
        public string Reference_Of_Walk_In { get; set; }
        public string DeletedBy { get; set; }
        public string AadharNo { get; set; }
        public string PAN_Card { get; set; }
        public string CustomMemberID { get; set; }
        public string FatherName { get; set; }
        public string Additional_Notes { get; set; }
        public string Addon_Member { get; set; }
        public string Relationship { get; set; }
        public string JoiningDate { get; set; }
    
        public virtual ICollection<tbl_PermissionsToStaff> tbl_PermissionsToStaff { get; set; }
        public virtual tbl_Roles tbl_Roles { get; set; }
        public virtual ICollection<tbl_UserGroup> tbl_UserGroup { get; set; }
        public virtual ICollection<tbl_UserMembership> tbl_UserMembership { get; set; }
        public virtual ICollection<tbl_UsersStay> tbl_UsersStay { get; set; }
        public virtual ICollection<tbl_VoucherUsedByUser> tbl_VoucherUsedByUser { get; set; }
    }
}
