//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildCrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Groups
    {
        public tbl_Groups()
        {
            this.tbl_UserGroup = new HashSet<tbl_UserGroup>();
        }
    
        public int ID { get; set; }
        public string GroupName { get; set; }
        public string GroupDetail { get; set; }
    
        public virtual ICollection<tbl_UserGroup> tbl_UserGroup { get; set; }
    }
}
