//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildCrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EventsImgVideo
    {
        public int ID { get; set; }
        public Nullable<int> EventID { get; set; }
        public string Img_Video_Path { get; set; }
    
        public virtual tbl_Events tbl_Events { get; set; }
    }
}
