//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildCrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Voucher
    {
        public tbl_Voucher()
        {
            this.tbl_VoucherUsedByUser = new HashSet<tbl_VoucherUsedByUser>();
        }
    
        public int ID { get; set; }
        public string VoucherName { get; set; }
        public string VoucherDetails { get; set; }
        public string AddedBy { get; set; }
        public Nullable<bool> VoucherForApprvFrmSuperAdm { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual ICollection<tbl_VoucherUsedByUser> tbl_VoucherUsedByUser { get; set; }
    }
}
