//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildCrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RoomBooking_Details
    {
        public int ID { get; set; }
        public Nullable<int> Booking_ID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> NoOfPerson { get; set; }
        public Nullable<bool> ExtraBed { get; set; }
        public Nullable<int> ComplementaryStays { get; set; }
        public Nullable<double> TAmtPerRoom { get; set; }
    }
}
