//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildCrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BarMenu
    {
        public int ID { get; set; }
        public string Item_Name { get; set; }
        public string Details { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<bool> NewItemApprvFrmSuperAdm { get; set; }
        public Nullable<bool> DelItemApprvFromSuperAdm { get; set; }
        public string FoodType { get; set; }
        public string AddedBy { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<int> InventoryID { get; set; }
    }
}
