//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildCrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VoucherUsedByUser
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> VoucherID { get; set; }
    
        public virtual tbl_Voucher tbl_Voucher { get; set; }
        public virtual tbl_Profile tbl_Profile { get; set; }
    }
}
