//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildCrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RoomBilling
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string PhoneNo { get; set; }
        public string RoomID { get; set; }
        public string CheckInDate_ { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> SGST { get; set; }
        public Nullable<double> CGST { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<double> AdvancedPayment { get; set; }
        public Nullable<double> AmtToBePaid { get; set; }
    }
}
