//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildCrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Party_FoodMenu
    {
        public int Food_menu_Id { get; set; }
        public Nullable<int> Party_ID { get; set; }
        public Nullable<int> Buffet_Menu_Id { get; set; }
    }
}
