//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildCrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WineInventory
    {
        public int ID { get; set; }
        public string Item_Name { get; set; }
        public string Type { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string Added_Date { get; set; }
        public string Measurement { get; set; }
    
        public virtual tbl_Vendors tbl_Vendors { get; set; }
    }
}
