//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildCrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TablesForBooking
    {
        public int ID { get; set; }
        public string TableNo { get; set; }
        public string Table_Status { get; set; }
        public string Bar_Status { get; set; }
        public string Wine_Status { get; set; }
    }
}
