//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildCrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Roles
    {
        public tbl_Roles()
        {
            this.tbl_Profile = new HashSet<tbl_Profile>();
        }
    
        public int ID { get; set; }
        public string UserType { get; set; }
    
        public virtual ICollection<tbl_Profile> tbl_Profile { get; set; }
    }
}
